changelog:
  exclude:
    labels:
      - type/chore
      - type/test
  categories:
    - title: Features
      labels:
        - type/feature
    - title: Fixes
      labels:
        - type/bug
    - title: Performance
      labels:
        - type/perf
    - title: Documentation
      labels:
        - type/docs
    - title: Refactors
      labels:
        - type/refactor
    - title: Other Changes
      labels:
        - '*'
